name=input("Enter your name:")
age=input("Enter your age:")
gpa=input("Enter your gpa:")
print("student information")
print("-------------------")
print("name="+name)
print("age="+age)
print("gpa="+gpa)